export type Task = {
	id: string;
	status: 'queued' | 'running' | 'success' | 'failed';
	statusLabel: string;
	title: string;
	technicalSummary?: string;
	repoOwner?: string;
	repo: string;
	issueNumber?: number;
	branch?: string;
	issue: string;
	agent: string;
	progress: number;
	started: string;
	expanded: boolean;
	logs: Array<{ time: string; level: string; message: string }>;
	prUrl?: string;
	prNumber?: number;
	issueUrl?: string;
	commitHash?: string;
	git?: { add: number; remove: number };
};
